### ISSUE TITLE
XMLRPC requirement 

### ISSUE THREAD

**Issue by larry-perry** [sinisterchipmunk/gravatar#20]
Howdy,

I believe the newer versions of Ruby have removed xmlrpc support.  It's available as a gem though. Could the xmlrpc gem be added as a dependency of this gem?

Thanks!

**Comment by mattsly** [comment]
👍  - on Rails 5.1.2 and hit this

simple work around is to add `gem 'xmlrpc'` to the Gemfile...but would be nice to at least have that doc'ed

**Comment by Jaydenpis** [comment]
Yes
